### PR TITLE
Milestone 4

### PR DESCRIPTION
**Pull request by dibdas**
Magic-Books Inc. requested one additional functionality to be added to the application. They would like to be able to filter books in the table by category. It will add a new presentational component (CategoryFilter) which will just be a simple select box. In addition, we’ll create a new Redux action (CHANGE_FILTER) and a filter.js reducer.

### CODE REVIEW

**Comment by rukundoeric** [comment]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - Follows gitwork-flow.  💯
  - Codebase looks clean and professional. 💯 

- ### To Improve
  - [x] [MANDATORY] You over-used `// eslint-disable-line` statement. This is like making changes in Eslint config. they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/) and [Zendesk](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-)). kindy try to fix the errors instead of ignoring them.them.
  - [x] [MANDATORY] Remember, commit messages should be concise and descriptive and they should always be in imperative form. that means instead of saying `added filter reducer` it is better to say `add filter reducer`.
  - [x] [MANDATORY] Your app is throwing this error when I try to click on submit button. Kindly address it and fix it.
   Screen Shot 2021-07-20 at 20 50 49

  
_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

**Review by afanimartin — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work on making the requested changes. However, you missed to fix an error pointed out.
- Your app still throws the error: `Uncaught TypeError: dispatch is not a function` upon clicking the `Submit` button


### Martin Afani
#### Slack: whiz25

**Comment by dibdas** [comment]
> ## Changes Required 🙏🏿 🙏🏿 🙏🏿
> Nice work on making the requested changes. However, you missed to fix an error pointed out.
> 
> * Your app still throws the error: `Uncaught TypeError: dispatch is not a function` upon clicking the `Submit` button
> 
> ### Martin Afani
> #### Slack: whiz25

the error is not showing in my machine

**Review by Elbie-em — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED 🟡  ♻️ 

Hi team, great effort making it this far. It seems that they are some bugs in your project that need to be addressed before this milestone is approved. Check ⬇️ 

- [x] Kindly fix the errors below,
Screenshot 2021-07-21 at 15 21 52

- [x] When choose a category, the input fields value changes to the name of the category as shown below. Kindly fix this.
Screenshot 2021-07-21 at 15 23 34

- [x] It seems your previous fix caused a bug of not being able to add new books when submit is clicked, kindly fix this.

*All the best and keep up the good work* 💪 

### *Request another review once you have applied these fixes*

> Elbie Moonga (Part-time TSE)

> Github (@Elbie-em)
> Slack (Elbie Moonga)
> Twitter ([@ElbieEm](https://twitter.com/ElbieEm))
> LinkedIn([Elbie Moonga](https://www.linkedin.com/in/elbiemoonga/))

**Review by afanimartin — APPROVED** [review]
## Approved 👍🏿 👍🏿 👍🏿 
Nice work making the requested changes. Merge and proceed to the next milestone.


### Martin Afani
#### Slack: whiz25

**Pull request merged**
