### PR TITLE
Milestone 5

### PR DESCRIPTION
**Pull request by dibdas**
Have implemented all the frontend functionality of the bookstore management app using React and Redux. In this milestone, you will follow the provided design specs to build a UI for app.

### CODE REVIEW

**Review by oloomoses — CHANGES_REQUESTED** [review]
## Hello @dibdas,
**You have done a commendable job on this milestone**

However, there are some changes to be made before you can move forward
- [ ] The category filter is not working. Kindly ensure that the books are filtered when a category is selected
- [ ] Kindly check the below errors displayed in the browser console and fix them.
Screenshot from 2021-07-27 17-31-23
- [ ] Kindly update the deployed live version to match the local one.
- [ ] Let us kindly use this screenshot as a guide in implementing our specified design
Screenshot from 2021-07-27 18-11-36
The category and `Add book` texts are a little bit faded. `edit`, `remove`, `Author`, and `comments` texts are blue. `Completed` and `Current Chapter` text are faded
- [ ] The filter should be in the page header beside the CATEGORIES placeholder.


**Please make the above change and ask for another review**

Feel free to leave a comment while mentioning me and I will be happy to reply.
### Happy Coding
_Slack: Oloo Moses_

**Comment by bellom** [comment]
> ## Hello @dibdas,
> **You have done a commendable job on this milestone**
> 
> However, there are some changes to be made before you can move forward
> 
> * [ ]  The category filter is not working. Kindly ensure that the books are filtered when a category is selected
> * [ ]  Kindly check the below errors displayed in the browser console and fix them.
>   Screenshot from 2021-07-27 17-31-23
> * [ ]  Kindly update the deployed live version to match the local one.
> * [ ]  Let us kindly use this screenshot as a guide in implementing our specified design
>   Screenshot from 2021-07-27 18-11-36
>   The category and `Add book` texts are a little bit faded. `edit`, `remove`, `Author`, and `comments` texts are blue. `Completed` and `Current Chapter` text are faded
> * [ ]  The filter should be in the page header beside the CATEGORIES placeholder.
> 
> **Please make the above change and ask for another review**
> 
> Feel free to leave a comment while mentioning me and I will be happy to reply.
> 
> ### Happy Coding
> _Slack: Oloo Moses_

@dibdas In this re-review, let's make sure you fix all issues mentioned by the previous reviewer.

1. * [x]  Kindly update the deployed live version to match the local one.
2. Your design looks great but let's stick to the project requirement as we both know the rest of the students are following this design, let's adjust to being fair.
image

3.. Perhaps while trying to fix the code, we got our remove button messed up, kindly look into it and fix it.
     In another word; the `remove` button is not working, I couldn't remove a book.

**Review by bellom — CHANGES_REQUESTED** [review]
## Hi @dibdas   :clap: 

**Great work making `almost` all the necessary corrections from the previous review.**

# Status: Changes Required! ♻️ 

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Review by bellom — CHANGES_REQUESTED** [review]
## Hi @dibdas   :clap: 

# Status: Changes Required! ♻️ 

**For some reason, I'm not seeing any of your changes,  kindly double-check if you push the latest code.**

1. * [x]  Kindly update the deployed live version to match the local one.

Your local:
image

Your live link:
image


2. Your design looks great but let's stick to the project requirement as we both know the rest of the students are following this design, let's adjust to being fair.
image

Project Design:
image

**Hint:**
_1. Change the background color to fit in with the project design.
2. Change the text color (author, comment and remove) to fit in with the project design._

3.. Perhaps while trying to fix the code, we got our remove button messed up, kindly look into it and fix it.
     In another word; the `remove` button is not working, I couldn't remove a book.


### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best**

**Review by afanimartin — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work making the requested changes to the app's design.

### Changes 🔕 🔕 🔕 
- the design is still not looking like the give mock-up. the list of books, user avatar, and the `Add Book` button must all be aligned vertically.

#### Check the original design
main-ui

### Martin Afani
#### Slack: whiz25

**Review by afanimartin — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
You haven't made the changes I requested. The avatar and `Add Book` button are not aligned with the list of books vertically.
Make the change and send for another review.


### Martin Afani
#### Slack: whiz25

**Review by oloomoses — APPROVED** [review]
## Congratulations, Milestone Approved. :muscle: :tada: :clap: 
**Hello @dibdas,
Great job working on the changes suggested.
You have passed all the requirements for this milestone :muscle:**

Feel free to merge and close this pull request.

**I wish you the best in your next project and see you at the top :rocket:** 
#### Happy Coding
_Slack: Oloo Moses_

**Pull request merged**
